"""Adapt Langfuse's official docker-compose.yml for a private, local install.

Reads official-compose.yml (a pinned copy of Langfuse's own file) and writes
docker-compose.yml with these changes:
  - only the web UI/API is published, and only on 127.0.0.1; the database,
    ClickHouse, Redis, MinIO and the worker stay inside the Docker network
    (the official file also publishes Postgres on 5432, which would collide
    with this machine's own Postgres);
  - Langfuse's anonymous usage telemetry is off;
  - public sign-up is off: users are created by the setup script or an admin.
Secrets are never written here; they come from .env, generated by setup.sh.
"""
import sys

import yaml

SRC, DST = "official-compose.yml", "docker-compose.yml"

with open(SRC) as f:
    compose = yaml.safe_load(f)

for name, service in compose["services"].items():
    if name == "langfuse-web":
        service["ports"] = ["127.0.0.1:${LANGFUSE_PORT:-3000}:3000"]
        service["environment"]["AUTH_DISABLE_SIGNUP"] = "true"
    else:
        service.pop("ports", None)
    env = service.get("environment")
    if isinstance(env, dict) and "TELEMETRY_ENABLED" in env:
        env["TELEMETRY_ENABLED"] = "false"

header = ("# Generated by make_compose.py from official-compose.yml. Do not edit by hand.\n"
          "# Start with setup.sh, which also creates the secrets in .env.\n")
with open(DST, "w") as f:
    f.write(header)
    yaml.safe_dump(compose, f, sort_keys=False, default_flow_style=False, width=120)
print(f"wrote {DST}", file=sys.stderr)
