#!/bin/bash
# Start a private Langfuse on this machine and write the keys the pipeline needs.
#
#   deploy/langfuse/setup.sh
#
# Creates (once, never overwritten):
#   deploy/langfuse/.env                   secrets for the containers      (mode 600)
#   ~/.config/sast-autofix/langfuse.env    host and API keys for the tool  (mode 600)
# Then starts Langfuse on http://127.0.0.1:3000. Nothing secret is printed.
set -euo pipefail
cd "$(dirname "$0")"
umask 077

rand_hex() { openssl rand -hex "$1"; }

if [ ! -f .env ]; then
  PUBLIC_KEY="pk-lf-$(cat /proc/sys/kernel/random/uuid)"
  SECRET_KEY="sk-lf-$(cat /proc/sys/kernel/random/uuid)"
  UI_PASSWORD="$(rand_hex 12)"
  MINIO_SECRET="$(rand_hex 16)"
  cat > .env <<ENV
# Generated by setup.sh. Keep private (mode 600); it is not committed.
LANGFUSE_PORT=3000
POSTGRES_PASSWORD=$(rand_hex 16)
CLICKHOUSE_PASSWORD=$(rand_hex 16)
REDIS_AUTH=$(rand_hex 16)
MINIO_ROOT_PASSWORD=$MINIO_SECRET
LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=$MINIO_SECRET
LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY=$MINIO_SECRET
LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY=$MINIO_SECRET
NEXTAUTH_SECRET=$(rand_hex 32)
NEXTAUTH_URL=http://127.0.0.1:3000
SALT=$(rand_hex 16)
ENCRYPTION_KEY=$(rand_hex 32)
DATABASE_URL=postgresql://postgres:\${POSTGRES_PASSWORD}@postgres:5432/postgres
LANGFUSE_INIT_ORG_ID=sast-autofix
LANGFUSE_INIT_ORG_NAME="SAST Autofix"
LANGFUSE_INIT_PROJECT_ID=sast-autofix
LANGFUSE_INIT_PROJECT_NAME="SAST Autofix"
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=$PUBLIC_KEY
LANGFUSE_INIT_PROJECT_SECRET_KEY=$SECRET_KEY
LANGFUSE_INIT_USER_EMAIL=admin@sast-autofix.local
LANGFUSE_INIT_USER_NAME=admin
LANGFUSE_INIT_USER_PASSWORD=$UI_PASSWORD
ENV
  echo "created deploy/langfuse/.env (UI login: admin@sast-autofix.local, password is in that file)"
fi

# Keys for the pipeline: the host plus the project's API keys, same values as above.
mkdir -p "$HOME/.config/sast-autofix"
if [ ! -f "$HOME/.config/sast-autofix/langfuse.env" ]; then
  # Read single keys; never source .env (values may contain spaces).
  get() { grep -E "^$1=" .env | head -1 | cut -d= -f2-; }
  cat > "$HOME/.config/sast-autofix/langfuse.env" <<ENV
LANGFUSE_HOST=http://127.0.0.1:$(get LANGFUSE_PORT)
LANGFUSE_PUBLIC_KEY=$(get LANGFUSE_INIT_PROJECT_PUBLIC_KEY)
LANGFUSE_SECRET_KEY=$(get LANGFUSE_INIT_PROJECT_SECRET_KEY)
ENV
  echo "created ~/.config/sast-autofix/langfuse.env"
fi

python3 make_compose.py
docker compose --env-file .env up -d
echo "Langfuse is starting on http://127.0.0.1:3000 (first start takes a minute or two)"
