"""initial schema: runs and findings

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 21:23:53.919872
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('repository', sa.String(length=200), nullable=False),
    sa.Column('base_branch', sa.String(length=200), nullable=False),
    sa.Column('fix_branch', sa.String(length=200), nullable=True),
    sa.Column('commit', sa.String(length=64), nullable=True),
    sa.Column('trigger', sa.String(length=40), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scanned', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Integer(), nullable=False),
    sa.Column('fixed', sa.Integer(), nullable=False),
    sa.Column('review', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('residual', sa.Integer(), nullable=False),
    sa.Column('blocking', sa.Integer(), nullable=False),
    sa.Column('gate_passed', sa.Boolean(), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_url', sa.Text(), nullable=True),
    sa.Column('fix_branch_state', sa.String(length=20), nullable=True),
    sa.Column('fix_branch_description', sa.Text(), nullable=True),
    sa.Column('timings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_repo_branch_started', 'runs', ['repository', 'base_branch', 'started_at'], unique=False)
    op.create_index(op.f('ix_runs_repository'), 'runs', ['repository'], unique=False)
    op.create_index(op.f('ix_runs_started_at'), 'runs', ['started_at'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.Text(), nullable=False),
    sa.Column('cwe', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('owasp', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('file', sa.Text(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('laya_score', sa.Float(), nullable=False),
    sa.Column('route', sa.String(length=16), nullable=False),
    sa.Column('llm_label', sa.String(length=8), nullable=True),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('fix_validated', sa.Boolean(), nullable=False),
    sa.Column('fix_attempts', sa.Integer(), nullable=True),
    sa.Column('fix', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_fingerprint'), 'findings', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_findings_route'), 'findings', ['route'], unique=False)
    op.create_index(op.f('ix_findings_run_id'), 'findings', ['run_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_run_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_route'), table_name='findings')
    op.drop_index(op.f('ix_findings_fingerprint'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_runs_started_at'), table_name='runs')
    op.drop_index(op.f('ix_runs_repository'), table_name='runs')
    op.drop_index('ix_runs_repo_branch_started', table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
